[build]

Configuración para forzar a Netlify a no ejecutar comandos de compilación

command = "echo 'No build required'"

Directorio donde Netlify buscará los archivos a publicar (publicamos desde la raíz)

publish = "."
